exarch:
  os: debian
  description: Salt master master bootserver 
debian:
  os: debian
  description: debian install
arch:
  os: arch
  description: arch install
ubuntu:
  os: ubuntu
  description: ubuntu install

